name: Build Rust Project

on:
  workflow_dispatch: 

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      # - name: Install MinGW
        # run: choco install mingw -y
      # - name: Build Bullet Physics
        # shell: pwsh
        # run: Scripts/bullet.ps1
      - name: Build with Cargo
        run: cargo build --verbose
