name: Rust Tests

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ "1.85.0", "stable" ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c
      with:
        toolchain: ${{ matrix.rust }}
    - name: Check compilation
      run: cargo check --verbose
    - name: Run library tests
      run: cargo test --lib --verbose
    - name: Run integration tests
      run: cargo test --tests --verbose
    - name: Run doc tests
      run: cargo test --doc --verbose
